apiVersion: v1
kind: Pod
metadata:
  name: working
spec:
  containers:
    - name: working
      image: ubuntu:20.04
      command: ["/bin/bash", "-c", "--"]
      args: ["while true; do sleep 30; done;"]
      resources:
        requests:
          cpu: "100m"
          memory: "100M"
        limits:
          cpu: "1"
          memory: "4G"
