apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: my-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: try-envoy-ip
    networking.gke.io/managed-certificates: try-envoy-cert
spec:
  backend:
    serviceName: envoy
    servicePort: 8083
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: envoy
              servicePort: 8083
