namespace: try-envoy
bases:
  - ./envoy_cert
  - ./server1_cert
resources:
  - server1-deploy.yaml
  - server1-service.yaml
  # - ingress-cert.yaml
  # - envoy-deploy.yaml
  # - envoy-service.yaml
  # - envoy-ingress.yaml
# configMapGenerator:
#   - name: envoy-config
#     files:
#    null   - envoy.yaml
