namespace: try-envoy4
bases:
  - ./envoy_cert
  - ./server1_cert
resources:
  - server1-deploy.yaml
  - server1-service.yaml
  - envoy-deploy.yaml
  - envoy-service.yaml
  # - envoy-ingress.yaml
  # - ingress-cert.yaml
configMapGenerator:
  - name: envoy-config
    files:
      - envoy.yaml
